-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 18:22:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `idCursos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiantes` (
  `idestudiantes` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Edad` INT NULL,
  `Cursos_idCursos` INT NOT NULL,
  PRIMARY KEY (`idestudiantes`),
  INDEX `fk_estudiantes_Cursos_idx` (`Cursos_idCursos` ASC) VISIBLE,
  CONSTRAINT `fk_estudiantes_Cursos`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `mydb`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiantes_has_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiantes_has_Cursos` (
  `estudiantes_idestudiantes` INT NOT NULL,
  `Cursos_idCursos` INT NOT NULL,
  PRIMARY KEY (`estudiantes_idestudiantes`, `Cursos_idCursos`),
  INDEX `fk_estudiantes_has_Cursos_Cursos1_idx` (`Cursos_idCursos` ASC) VISIBLE,
  INDEX `fk_estudiantes_has_Cursos_estudiantes1_idx` (`estudiantes_idestudiantes` ASC) VISIBLE,
  CONSTRAINT `fk_estudiantes_has_Cursos_estudiantes1`
    FOREIGN KEY (`estudiantes_idestudiantes`)
    REFERENCES `mydb`.`estudiantes` (`idestudiantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `mydb`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nombres` VARCHAR(45) GENERATED ALWAYS AS (),
  `RUT` INT NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendedores` (
  `idVendedores` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `RUT` INT NULL,
  `Año ingreso` INT NULL,
  `Sucursal` VARCHAR(45) NULL,
  PRIMARY KEY (`idVendedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autos` (
  `idAutos` INT NOT NULL,
  `Patente` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Color` VARCHAR(45) NULL,
  `Precio` INT NULL,
  `Estado` TINYINT NULL,
  `Año` INT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Vendedores_idVendedores` INT NOT NULL,
  PRIMARY KEY (`idAutos`, `Clientes_idClientes`, `Vendedores_idVendedores`),
  INDEX `fk_Autos_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Autos_Vendedores1_idx` (`Vendedores_idVendedores` ASC) VISIBLE,
  CONSTRAINT `fk_Autos_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autos_Vendedores1`
    FOREIGN KEY (`Vendedores_idVendedores`)
    REFERENCES `mydb`.`Vendedores` (`idVendedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mantencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mantencion` (
  `idMantencion` INT NOT NULL,
  `Fecha visita` VARCHAR(45) NULL,
  `Codigo Atencion` INT NULL,
  `Cambio Filtro` TINYINT NULL,
  `Cambio Aceite` TINYINT NULL,
  `Cambio Neumaticos` TINYINT NULL,
  `Comentarios adicionales` VARCHAR(45) NULL,
  PRIMARY KEY (`idMantencion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mantencion_has_Autos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mantencion_has_Autos` (
  `Mantencion_idMantencion` INT NOT NULL,
  `Autos_idAutos` INT NOT NULL,
  `Autos_Clientes_idClientes` INT NOT NULL,
  `Autos_Vendedores_idVendedores` INT NOT NULL,
  PRIMARY KEY (`Mantencion_idMantencion`, `Autos_idAutos`, `Autos_Clientes_idClientes`, `Autos_Vendedores_idVendedores`),
  INDEX `fk_Mantencion_has_Autos_Autos1_idx` (`Autos_idAutos` ASC, `Autos_Clientes_idClientes` ASC, `Autos_Vendedores_idVendedores` ASC) VISIBLE,
  INDEX `fk_Mantencion_has_Autos_Mantencion1_idx` (`Mantencion_idMantencion` ASC) VISIBLE,
  CONSTRAINT `fk_Mantencion_has_Autos_Mantencion1`
    FOREIGN KEY (`Mantencion_idMantencion`)
    REFERENCES `mydb`.`Mantencion` (`idMantencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mantencion_has_Autos_Autos1`
    FOREIGN KEY (`Autos_idAutos` , `Autos_Clientes_idClientes` , `Autos_Vendedores_idVendedores`)
    REFERENCES `mydb`.`Autos` (`idAutos` , `Clientes_idClientes` , `Vendedores_idVendedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
